AWSTemplateFormatVersion: '2010-09-09'
Description: demo

Resources:
  MyInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08188a5a4dfdbd573
      InstanceType: t3.micro
      KeyName: 9-30am-july-26
      SecurityGroupIds:
              - !Ref MyInstanceSecurityGroup
      Tags:
        - Key: Name
          Value: 9am-srv
